apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-go-echo
  labels:
    app: go-echo
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: go-echo
  template:
    metadata:
      labels:
        app: go-echo
    spec:
      containers:
        - name: go-echo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
