apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-go-echo
  labels:
    app: go-echo
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: go-echo
